### PR TITLE
Omnichat Module docs

### PR DESCRIPTION
**Pull request by resir014**

### CODE REVIEW

**Comment by resir014** [comment]
@mochaul Done.

> Then, add a new page: http://docs.kata.ai/module/omnichat/introduction

This can only be put on `/modules/module-list/omnichat/introduction`, to follow the document structure.

**Comment by mochaul** [comment]
Thank you @resir014 ! `/modules/module-list/omnichat/introduction` would be fine 👍

**Comment by resir014** [comment]
@mochaul It's been done. Please review again.

**Comment by mochaul** [comment]
Nice, thank you @resir014 ! Can you add this also please:

add a new page:
http://docs.kata.ai/module/omnichat/introduction

that contains this markdown:
https://kata.quip.com/uihwAWATDmXA/Introduction-to-Kata-Omnichat

Thank you @resir014

**Comment by resir014** [comment]
It's here:

https://deploy-preview-93--kata-platform-docs.netlify.com/modules/module-list/omnichat/introduction/

This is still not merged to production, so it's not in the `docs.kata.ai` url.

**Comment by mochaul** [comment]
Thank you so much @resir014 ! All good.

**Pull request merged**
